### ISSUE TITLE
FsLab Basic Template Demo Has Error -- Tutorial.fsx

### ISSUE THREAD

**Issue by NatElkins** [fslaborg/FsLab.Templates#5]
Hi,

The Tutorial.fsx file that is part of basic.zip has an error.  In the file, the WorldBankData type provider is used to compare data from the Czech Republic and the EU.  The indicators that are used, though, do not exist.  Specifically, on these lines:

```F#
// Use Deedle to get time-series with school enrollment data
let czschool = series cz.``School enrollment, tertiary (% gross)``
let euschool = series eu.``School enrollment, tertiary (% gross)``
```

I get an error using Atom, VS Code, and MonoDevelop (using Ubuntu 15.04).

See here:

![wbdprovidererror](https://cloud.githubusercontent.com/assets/1795462/11536550/e47df3d4-98e6-11e5-95a0-f1aa7d855567.png)

This particular indicator should be changed.

**Comment by tpetricek** [comment]
Oh no, World Bank regularly renames the indicators to make our life more fun :-).

If you can send a PR that uses the new names, that would be fantastic!

**Comment by NatElkins** [comment]
Closing as per https://github.com/fslaborg/FsLab.Templates/pull/10
